stages:
  - validate

yamllint:
  stage: validate
  image: cytopia/yamllint:latest
  script:
    - echo "Linting YAML files..."
    - yamllint -d "{extends: default, rules: {line-length: disable}}" .

