stages:
  - validate

validate-manifests:
  stage: validate
  script:
    - echo "Validating YAML files (syntax only, no API server)..."
    - |
      for f in $(find . -type f \( -name "*.yaml" -o -name "*.yml" \) ! -name ".gitlab-ci.yml"); do
        echo "Validating $f"
        kubectl apply --dry-run=client --validate=false -f "$f" >/dev/null
      done

