stages:
  - validate

validate-manifests:
  stage: validate
  script:
    # Fail fast on errors
    - set -e
    # Show kubectl version (sanity check)
    - kubectl version --client
    # Validate all YAMLs in repo (client-side only, no cluster apply)
    - kubectl apply --dry-run=client -f .

