stages:
  - validate

validate-manifests:
  stage: validate
  script:
    - echo "Validating YAML files..."
    # Loop through only *.yaml and *.yml files, skip .gitlab-ci.yml
    - |
      for f in $(find . -type f \( -name "*.yaml" -o -name "*.yml" \) ! -name ".gitlab-ci.yml"); do
        echo "Validating $f"
        kubectl apply --dry-run=client --validate=false -f "$f"
      done

