stages:
  - validate

validate-manifests:
  stage: validate
  script:
    - echo "Validating YAML files..."
    # Apply only .yaml/.yml files, ignore .gitlab-ci.yml
    - find . -name "*.yaml" -o -name "*.yml" | xargs kubectl apply --dry-run=client --validate=false -f

