stages:
  - validate

validate-manifests:
  stage: validate
  script:
    - echo "Validating YAML files (client-side only)..."
    - |
      for f in $(find . -type f \( -name "*.yaml" -o -name "*.yml" \) ! -name ".gitlab-ci.yml"); do
        echo "Validating $f"
        kubectl create --dry-run=client -f "$f" >/dev/null
      done

