name: Mirror to GitLab

on:
  push:            # run for all branches & tags
    branches: ['**']
    tags:     ['**']

concurrency:
  group: mirror-to-gitlab
  cancel-in-progress: true

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history (branches + tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add GitLab remote (using token)
        env:
          GITLAB_URL:   ${{ secrets.GITLAB_URL }}
          GITLAB_USER:  ${{ secrets.GITLAB_USER }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          # Avoid printing token in logs
          set -euo pipefail
          git config --global user.name  "github-actions"
          git config --global user.email "actions@users.noreply.github.com"
          git remote add gitlab "https://${GITLAB_USER}:${GITLAB_TOKEN}@${GITLAB_URL#https://}"

      # If a branch was pushed, update that branch and tags
      - name: Push branch + tags to GitLab
        if: startsWith(github.ref, 'refs/heads/')
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          # Push the branch that triggered the workflow
          git push --force-if-includes --atomic gitlab "HEAD:refs/heads/${REF_NAME}"
          # Push any new/updated tags too
          git push --tags gitlab

      # If a tag was pushed, update that tag in GitLab
      - name: Push tag to GitLab
        if: startsWith(github.ref, 'refs/tags/')
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          git push --atomic gitlab "refs/tags/${REF_NAME}:refs/tags/${REF_NAME}"
